const productImage = "https://fajaskayros.com/wp-content/uploads/2024/06/shortdubaiinvisibleppal-500x500.jpg";
const products = [
  ["Short Pesquero Invisible Dubai", "$105,000.00", "short", "shortdubaiinvisibleppal-500x500.jpg", "short-pesquero-invisible-dubai"], ["Short Invisible Venecia", "$99,900.00", "short", "shortveneciainvisibleppal-500x500.jpg", "short-invisible-venecia"], ["Panty Short Cachetero Nicol", "$75,000.00", "short", "shortnicollppal-500x500.jpg", "panty-short-cachetero-nicol"], ["Short Levanta Cola Paris", "$95,000.00", "short", "shortparisppal-500x500.jpg", "short-levanta-cola-paris"], ["Short Levanta Cola Invisible Adonai", "$95,000.00", "short", "shortadonaiinvisibleppal-500x500.jpg", "short-levanta-cola-invisible-adonai"], ["Short Levanta Cola Mónaco", "$90,000.00", "short", "pantyshortmonacobeigeppal-500x500.jpg", "short-levanta-cola-monaco"],
  ["Cintura de Sirena Dayana 13 varillas", "$139,900.00", "control", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "cintura-de-sirena-dayana-13-varillas"], ["Cintura de Sirena Dayana 15 varillas", "$149,900.00", "control", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "cintura-de-sirena-dayana-15-varillas"], ["Leggins Faja con Cinturilla Látex", "$120,000.00", "control", "https://fajaskayros.com/wp-content/uploads/2026/03/laterales-cuadrados-500x500.png", "leggins-faja-con-cinturilla-latex"], ["Jean Push Up Dama Faja", "$129,900.00", "faja", productImage, "jean-push-up-dama-faja"], ["Short Push Up Milan", "$85,000.00", "short", productImage, "short-push-up-milan"], ["Short Push Up Milano", "$95,000.00", "short", productImage, "short-push-up-milano"],
  ["Short Levanta Cola Charlotte", "$85,000.00", "short", "shortparisppal-500x500.jpg", "short-levanta-cola-charlotte"], ["Short Levanta Cola Salma", "$85,000.00", "short", productImage, "short-levanta-cola-salma"], ["Faja Strapless Antonella", "$130,000.00", "faja", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "faja-strapless-antonella"], ["Faja Tipo Short Keyla", "$129,900.00", "faja", productImage, "faja-tipo-short-keyla"], ["Faja Danna", "$165,000.00", "faja", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "faja-danna"], ["Faja Tipo Short Daniela", "$165,000.00", "faja", productImage, "faja-tipo-short-daniela"],
  ["Faja Tipo Short Laura", "$165,000.00", "faja", productImage, "faja-tipo-short-laura"], ["Faja Strapless Violet", "$130,000.00", "faja", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "faja-strapless-violet"], ["Faja Tira Ancha Penelope", "$165,000.00", "faja", productImage, "faja-tira-ancha-penelope"], ["Faja con Mangas Sofia", "$165,000.00", "faja", productImage, "faja-con-mangas-sofia"], ["Faja Pescador Tannia", "$185,000.00", "faja", "https://fajaskayros.com/wp-content/uploads/2024/02/Dayana-4-1.png", "faja-pescador-tannia"], ["Faja Panty Body", "$95,000.00", "faja", productImage, "faja-panty-body"]
].map(([name, price, category, image, slug]) => ({ name, price, category, image: image.startsWith("http") ? image : `https://fajaskayros.com/wp-content/uploads/2024/06/${image}`, url: `https://fajaskayros.com/producto/${slug}/` }));

const productGrid = document.querySelector("#product-grid"); const productCount = document.querySelector("#product-count"); const filters = document.querySelectorAll(".filter"); const menuButton = document.querySelector(".menu-button"); const siteMenu = document.querySelector("#site-menu");
function renderProducts(filter = "all") { const visible = filter === "all" ? products : products.filter((product) => product.category === filter); productCount.textContent = `${visible.length} ${visible.length === 1 ? "prenda" : "prendas"}`; productGrid.innerHTML = visible.map((product) => `<article class="product-card"><a class="product-image" href="${product.url}" target="_blank" rel="noopener"><img src="${product.image}" alt="${product.name}" loading="lazy" /></a><div class="product-body"><span class="product-category">${product.category}</span><h3>${product.name}</h3><div class="product-meta"><span class="price">${product.price}</span><a class="view-product" href="${product.url}" target="_blank" rel="noopener">Ver ↗</a></div></div></article>`).join(""); }
filters.forEach((button) => button.addEventListener("click", () => { filters.forEach((item) => item.classList.remove("is-active")); button.classList.add("is-active"); renderProducts(button.dataset.filter); }));
menuButton.addEventListener("click", () => { const open = siteMenu.classList.toggle("is-open"); menuButton.setAttribute("aria-expanded", String(open)); menuButton.querySelector("span").textContent = open ? "−" : "+"; });
siteMenu.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => { siteMenu.classList.remove("is-open"); menuButton.setAttribute("aria-expanded", "false"); menuButton.querySelector("span").textContent = "+"; })); renderProducts();
